# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('sex', models.CharField(choices=[('Others', 'Others'), ('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
            ],
            options={
                'verbose_name': 'Users Info',
                'verbose_name_plural': 'Users Info',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_no', models.PositiveIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('joining_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('u_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='of user'),
        ),
    ]
