# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 17:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171112_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='area_code',
            field=models.PositiveIntegerField(default=100001, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100001)]),
        ),
    ]
