# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 18:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0002_auto_20171110_1015'),
        ('users', '0005_auto_20171113_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pin_code',
            field=models.PositiveIntegerField(default=100001, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100001)]),
        ),
        migrations.AddField(
            model_name='users',
            name='subs_paper',
            field=models.ManyToManyField(related_name='papers_sub', to='newspapers.Newspapers', verbose_name='subscribed for'),
        ),
    ]
