# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180410_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='subs_paper',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
