# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pin_code',
        ),
    ]
