# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180411_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_bill',
            field=models.FloatField(default=0),
        ),
    ]
