# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-14 17:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newspapers', '__first__'),
        ('users', '0001_initial'),
        ('Vendor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, max_length=8)),
                ('address', models.TextField(default='default')),
                ('pin_code', models.PositiveIntegerField(default=100001, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100001)])),
                ('days', models.IntegerField(default=0)),
                ('bill', models.FloatField(default=0)),
                ('skip', models.IntegerField(default=0)),
                ('sub_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers_subs', to='newspapers.Newspapers', verbose_name='subscribe for')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='users.Users', verbose_name='subscriber')),
                ('vendor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Vendor.Vendor')),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, max_length=8)),
                ('address', models.TextField(default='default')),
                ('pin_code', models.PositiveIntegerField(default=100001, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100001)])),
                ('sub_paper', models.ManyToManyField(related_name='papers_subscribed', to='newspapers.Newspapers', verbose_name='subscribed for')),
                ('sub_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_by_user', to='users.Users', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': ' Subscriptions',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
