# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 21:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pin_code',
            field=models.PositiveIntegerField(default=100001, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100001)]),
        ),
    ]
