# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-10 12:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0002_auto_20171110_1015'),
        ('users', '0012_auto_20171228_1615'),
        ('news_subscription', '0002_subscription_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, max_length=8)),
                ('address', models.TextField(default='default')),
                ('pin_code', models.PositiveIntegerField(default=100001, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100001)])),
                ('sub_paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='papers_subs', to='newspapers.Newspapers', verbose_name='subscribed for')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='users.Users', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
            },
        ),
    ]
