# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0003_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='sub_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers_subs', to='newspapers.Newspapers', verbose_name='subscribed for'),
        ),
    ]
