# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0005_auto_20180410_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepaper',
            name='bill',
            field=models.FloatField(default=0),
        ),
    ]
