# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0007_subscribepaper_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepaper',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribepaper',
            name='sub_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers_subs', to='newspapers.Newspapers', verbose_name='subscribe for'),
        ),
    ]
