# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-13 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0010_auto_20180413_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribepaper',
            name='vendor',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
