# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pincode',
                'verbose_name_plural': 'Pincode',
            },
        ),
    ]
