# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Available',
                'verbose_name_plural': 'Available',
            },
        ),
    ]
