# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0002_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='pincode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pincode.Pincode'),
        ),
    ]
