# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0003_auto_20171228_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
