# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Kannada', 'Kannada'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu'), ('Bengali', 'Bengali')], max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('All Days', 'All Days'), ('Weekends', 'Weekends'), ('Weekdays', 'Weekdays'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=83)),
                ('area', multiselectfield.db.fields.MultiSelectField(choices=[('Powai', 'Powai'), ('Ghansoli', 'Ghansoli')], max_length=14)),
                ('timing', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
            ],
            options={
                'verbose_name': 'Newspapers',
                'verbose_name_plural': 'Newspapers',
            },
        ),
    ]
