# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspapers',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Powai', 'Powai'), ('Ghansoli', 'Ghansoli')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='newspapers',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('All Days', 'All Days'), ('Weekends', 'Weekends'), ('Weekdays', 'Weekdays'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='newspapers',
            name='timing',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20, null=True),
        ),
    ]
