# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='namee')),
                ('tempw', models.CharField(default='temp', max_length=22)),
                ('genre_img', models.ImageField(blank=True, null=True, upload_to='genres_image')),
            ],
            options={
                'verbose_name': 'Genres',
                'verbose_name_plural': 'Genres',
            },
        ),
    ]
