# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newspapers', '0002_auto_20171110_1015'),
        ('users', '0017_users_total_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unpaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FloatField()),
                ('sub_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_paper', to='newspapers.Newspapers', verbose_name='subscribed for')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_subscriber', to='users.Users', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'Unpaid',
                'verbose_name_plural': 'Unpaids',
            },
        ),
    ]
