# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-14 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unpaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=8)),
                ('end_date', models.DateField(default=django.utils.timezone.now, max_length=8)),
                ('bill', models.FloatField()),
                ('sub_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_paper', to='newspapers.Newspapers', verbose_name='subscribed for')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_subscriber', to='users.Users', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'Unpaid',
                'verbose_name_plural': 'Unpaids',
            },
        ),
    ]
