# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unpaid', '0002_unpaid_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaid',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
        ),
        migrations.AlterField(
            model_name='unpaid',
            name='start_date',
            field=models.DateField(max_length=8),
        ),
    ]
