# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(verbose_name='topicss')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_of', to='genres.Genres')),
            ],
            options={
                'verbose_name': 'Topics',
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
